services:
  postgres:
    image: postgres:16-alpine
    container_name: checkers-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: checkers_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d checkers_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: